export default [
	{
		id: 1,
		name: `Mount Everest`,
		info: `Mount Everest attracts many climbers, including highly experienced mountaineers. There are two main climbing routes, one approaching the summit from the southeast in Nepal (known as the "standard route") and the other from the north in Tibet. While not posing substantial technical climbing challenges on the standard route, Everest presents dangers such as altitude sickness, weather, and wind, as well as hazards from avalanches and the Khumbu Icefall. As of 2019, over 300 people have died on Everest,[4] many of whose bodies remain on the mountain.`,
		image: `https://ychef.files.bbci.co.uk/976x549/p0c036vs.jpg`,
		price: `$45k`,
		height: `29,031.7 ft`,
	},
	{
		id: 2,
		name: `Aconcagua`,
		info: `Aconcagua is bounded by the Valle de las Vacas to the north and east and the Valle de los Horcones Inferior to the west and south. The mountain and its surroundings are part of the Aconcagua Provincial Park. The mountain has a number of glaciers. The largest glacier is the Ventisquero Horcones Inferior at about 10 km (6 mi) long, which descends from the south face to about 3,600 m (11,800 ft) in altitude near the Confluencia camp.[6] Two other large glacier systems are the Ventisquero de las Vacas Sur and Glaciar Este/Ventisquero Relinchos system at about 5 km (3 mi) long. The most well known is the north-eastern or Polish Glacier, as it is a common route of ascent.`,
		image: `https://res.cloudinary.com/dtpgi0zck/image/upload/s--__3ivQD8--/c_fill,h_580,w_860/v1/EducationHub/photos/cerro-aconcagua-peak.jpg`,
		price: `$15k`,
		height: `22,837 ft`,
	},
	{
		id: 3,
		name: `Denali`,
		info: `The Koyukon people who inhabit the area around the mountain have referred to the peak as "Denali" for centuries. In 1896, a gold prospector named it "Mount McKinley" in support of then-presidential candidate William McKinley; that name was the official name recognized by the federal government of the United States from 1917 until 2015. In August 2015, 40 years after Alaska had done so, the United States Department of the Interior announced the change of the official name of the mountain to Denali.`,
		image: `https://res.cloudinary.com/dtpgi0zck/image/upload/s--5Pb3YX9z--/c_fill,h_580,w_860/v1/EducationHub/photos/mount-denali-cloud.jpg`,
		price: `$10k`,
		height: `20,310 ft`,
	},
	{
		id: 4,
		name: `Mount Kilimanjaro`,
		info: `Mount Kilimanjaro is a dormant volcano in Tanzania. It has three volcanic cones: Kibo, Mawenzi, and Shira. It is the highest mountain in Africa and the highest single free-standing mountain above sea level in the world: 5,895 metres (19,341 ft) above sea level and about 4,900 metres (16,100 ft) above its plateau base. It is the highest volcano in Africa and the Eastern Hemisphere.`,
		image: `https://files.worldwildlife.org/wwfcmsprod/images/kilimanjaro_facts_travel_blog/story_full_width/7z41g35fwt_1203668448_73.jpg`,
		price: `$6k`,
		height: `19,341 ft`,
	},
	{
		id: 5,
		name: `Mount Vinson`,
		info: `Mount Vinson is the highest peak in Antarctica, at 4,892 metres (16,050 ft).[6] It lies in the north part of Vinson Massif's summit plateau in the south portion of the main ridge of the Sentinel Range about 2 kilometres (1+1⁄4 mi) north of Hollister Peak.[5] It was first climbed in 1966 by an American team led by Nicholas Clinch. An expedition in 2001 was the first to climb via the Eastern route, and also took GPS measurements of the height of the peak.[7] As of February 2010, 1,400 climbers have attempted to reach the top of Mount Vinson.`,
		image: `https://accounts.termwiki.com/images/thumb.png?f=mt-vinson-massif-161-1378359347.jpg`,
		price: `$16k`,
		height: `16,050 ft`,
	},
	{
		id: 6,
		name: `Mount Elbrus`,
		info: `Elbrus has two summits, both of which are dormant volcanic domes. The taller, western summit is 5,642 metres (18,510 ft);[2] the eastern summit is 5,621 metres (18,442 ft). The eastern summit was first ascended on 10 July 1829 by Khillar Khachirov, and the western summit in 1874 by a British expedition led by F. Crauford Grove and including Frederick Gardner, Horace Walker and the Swiss guide Peter Knubel.`,
		image: `https://cdn.mos.cms.futurecdn.net/F89hZTBM68FmFCPVEfmkA8.jpg`,
		price: `$5k`,
		height: `18,510 ft`,
	},
	{
		id: 7,
		name: `Mount Wilhelm`,
		info: `Mount Wilhelm (German: Wilhelmsberg) is the highest mountain in Papua New Guinea at 4,509 metres (14,793 ft). It is part of the Bismarck Range and the peak is the point where three provinces, Chimbu, Jiwaka and Madang, meet. The peak is also known as Enduwa Kombuglu, or Kombugl'o Dimbin, in the local Kuman. The mountain is on the island of New Guinea, which incorporates Papua New Guinea and the Indonesian province of Papua. It is surpassed by Puncak Jaya, 4,884 m (16,024 ft), and several other peaks in Indonesian Papua. Mount Wilhelm may be considered the highest mountain in Oceania (including Australia and New Zealand).[3] A Seven Summits list may therefore sometimes include Mount Wilhelm.`,
		image: `https://i.pinimg.com/originals/3c/c2/11/3cc2110c369fbf752b26f6ef1a3a1b6f.jpg`,
		price: `$6k`,
		height: `14,793 ft`,
	},
];
